apiVersion: batch/v1
kind: CronJob
metadata:
  name: speedtest
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: harbor.k01.satoruh.org/library/speedtest:latest
            name: speedtest
          restartPolicy: Never
